### ISSUE TITLE
check if css import works in custom elements

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#8]
update elements when
https://code.google.com/p/dart/issues/detail?id=14447
is fixed
- [x] polymer-collapse
- [x] polymer-flex-layout #29 
- [x] flex-css of example/polymer-flex-layout #29
- [x] polymer_ui_elements/polymer_ui_arrow ErikGrimes/polymer_ui_elements#13
